"""Added owner id to guild

Revision ID: 30bb934012b9
Revises: 345c70c3a7b1
Create Date: 2022-04-13 16:06:33.226280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "30bb934012b9"
down_revision = "345c70c3a7b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guild", sa.Column("owner_id", sa.BigInteger(), nullable=False))
    op.alter_column(
        "invites", "code", existing_type=mysql.VARCHAR(length=10), nullable=False
    )
    op.alter_column(
        "invites",
        "expires_at",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invites",
        "expires_at",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=True,
    )
    op.alter_column(
        "invites", "code", existing_type=mysql.VARCHAR(length=10), nullable=True
    )
    op.drop_column("guild", "owner_id")
    # ### end Alembic commands ###
