"""empty message

Revision ID: 6805f7360911
Revises: 70065dff8372
Create Date: 2022-04-12 17:54:44.894506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6805f7360911'
down_revision = '70065dff8372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=60),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
