"""Added uses field to invite

Revision ID: e23b26925b46
Revises: ee388de273db
Create Date: 2022-04-13 16:45:13.821331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e23b26925b46"
down_revision = "ee388de273db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invites", sa.Column("uses", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invites", "uses")
    # ### end Alembic commands ###
