"""Forgor to make invite code unique

Revision ID: ee388de273db
Revises: 30bb934012b9
Create Date: 2022-04-13 16:34:30.833200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee388de273db'
down_revision = '30bb934012b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invites', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    # ### end Alembic commands ###
